### ISSUE TITLE
Resources accessed through `PermissionClaim`s cannot allow privilege escalations

### ISSUE THREAD

**Issue by davidfestal** [kcp-dev/kcp#1337]
Resources accessed through `PermissionClaim`s cannot allow privilege escalations - see [this comment](https://github.com/kcp-dev/kcp/issues/1337#issuecomment-1229093358) for details

**Comment by davidfestal** [comment]
cc @ncdc @shawn-hurley

**Comment by ncdc** [comment]
I don't think we want to do this. The user is required to accept a permission claim before the associated resource(s) are visible through the APIExport virtual workspace. Once that claim is accepted, it's the equivalent of granting [verbs] to the APIExport serviceaccount.

**Comment by ncdc** [comment]
Discussed in community meeting today. Need to flesh out the details (this is a possible privilege escalation). @sttts @davidfestal

**Comment by pweil-** [comment]
@davidfestal this looks like it still needs details.  Still on the 0.8 list or do we need to push to 0.9?

**Comment by ncdc** [comment]
Filling in the details:

Let's say there are 2 API providers, in workspaces A and B.

A has an APIExport for Things and sets a local maximal permission policy that grants system:authenticated read-only verbs (get/list/watch).

B has an APIExport for Widgets, and it claims Things from A's APIExport.

A consumer in workspace C creates APIBindings for both A (Things) and B (Widgets, Things(claimed & accepted)).

When the consumer user in C tries to create a Thing, they're denied because of the maximal permission policy.

When provider B goes through their APIExport's virtual workspace and tries to create a Thing in workspace C, it should not be allowed, because of the maximal permission policy. But because the dynamic forwarding client in the virtual workspace code is using the loopback client, it has system:masters permission, and it doesn't go through authorization. Therefore, this request is allowed when it shouldn't be.

**Comment by MatousJobanek** [comment]
Just out of curiosity - couldn't this scenario be solved at the phase of accepting the claims? That the user could accept only those claims the user has permissions for? So if the user can only read the A Things, then the user cannot accept claims for write?

**Comment by ncdc** [comment]
No - this is about access through the APIExport virtual workspace by an API provider. This is currently done using the loopback client, which has `system:masters` access.

**Comment by ncdc** [comment]
@s-urbaniak FYI, @sttts wanted you to be aware of this. Probably can do this with a SAR of some sort against maximal permisison

**Comment by ncdc** [comment]
Moving to 0.9
