### ISSUE TITLE
Deployment’s creationTimestamp should not be mutable

### ISSUE THREAD

**Issue by kasturinarra** [kcp-dev/kcp#1647]
**Describe the bug**
kuard.yaml metadata is creationTimestamp: null , and kubectl get deployment -o yaml shows metadata creationTimestamp: null , this indicates creationTimestamp is not immutable and if you kubectl edit deployment to any invalid value for example creationTimestamp: "2000-07-29T08:50:59Z" and save, this can be successful!! And the AGE shows 22y

**To Reproduce**
1. Run command 'kubectl create deployment kuard1 --image gcr.io/kuar-demo/kuard-amd64:blue --dry-run=client -o yaml > kuard1.yaml'
2. Now edit kuard.yaml file and set Timestamp to "2000-07-29T08:50:59Z" and save, this can be successful!! And the AGE shows 22y

**Expected behavior**
creationTimestamp field should not be mutable.

**Additional context**

**Comment by ncdc** [comment]
Am able to reproduce

**Comment by ncdc** [comment]
This is happening only for built-in Kubernetes types that we are supporting as CRDs, such as Deployments. It does not happen with "normal" CRDs. The root cause is from https://github.com/kcp-dev/kubernetes/blob/b6a732dbd0139dc4a1f14ca188befc9bd56ade5b/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/patch.go#L526:

Because we support using CRDs to represent built-in Kubernetes types (e.g. deployments) that do support strategic patch, we have to make sure we deep copy originalObject if it's already unstructured.Unstructured, because runtime.DefaultUnstructuredConverter.ToUnstructured returns the underlying map from an Unstructured without copying it, meaning that the call to applyPatchToObject below mutates the original Unstructured content unless we've first made a deep copy.

Am working on an e2e test to ensure conformance + a fix.

**Comment by ncdc** [comment]
Kube fork fix: https://github.com/kcp-dev/kubernetes/pull/92
