### ISSUE TITLE
bug: kcp apiserver does not serve openapi specifications

### ISSUE THREAD

**Issue by stevekuznetsov** [kcp-dev/kcp#1818]
### Describe the bug

The `/clusters/foo/openapi` endpoints for kcp apiserver return the kubernetes OpenAPI spec.

### Steps To Reproduce

```
kubectl get --raw /openapi/v2 | grep ClusterWorkspace
```

### Expected Behaviour

We generate the definitions, so I imagine we want to serve them? This would also be nice to allow downstream users to generate clients in non-Go SDKs.

**Comment by ncdc** [comment]
Need to make sure we do this properly so we don't overload the server with too much OpenAPI generation across potentially hundreds/thousands of workspaces

**Comment by stevekuznetsov** [comment]
In addition to dynamically determining this based on bound APIs within a workspace, I think we can also get a lot of value today from having (semi-static) published definitions for the core `kcp` APIs so that devs could explore the API surface and e.g. generate clients for non-Go SDKs.

**Comment by astefanutti** [comment]
This should also fix #1449.

**Comment by ncdc** [comment]
Adding some more detail:

1. We are supposed to be including the built-in k8s types in our OpenAPI doc. But this is not happening at the moment because the MiniAggregatorConfig stores a pointer to a GenericConfig that is used by both it (mini aggregator) and the k8s control plane apiserver:

https://github.com/kcp-dev/kcp/blob/e40bffc1a67e56d780bc97b1ced45d0c1d7c786e/pkg/server/config.go#L520

This is a problem because in the mini aggregator code, we tell it to skip OpenAPI installation so we can install our own aggregated handler:

https://github.com/kcp-dev/kubernetes/blob/6ebb9f064d8cd524bafba7154d5e47619303be0a/pkg/genericcontrolplane/aggregator/aggregator.go#L103-L107

Unfortunately this is the same `GenericConfig`, which ends up disabling OpenAPI installation for the k8s control plane server.
