### ISSUE TITLE
[Contribution] bash script to start/stop/install/.... kcp

### ISSUE THREAD

**Issue by cmoulliard** [kcp-dev/kcp#1914]
## Contribution

I designed for demo purposes a bash script to start/stop/install/clean kcp on a mac or linux machine. If kcp' project is interested, the code of this script is available here and can be donated: https://github.com/ch007m/kcp/blob/main/kcp.sh

```
Usage:
  ./kcp.sh <command> [args]

Commands:
    install     Install the kcp server locally and kcp kubectl plugins
    start       Start the kcp server
    stop        Stop the kcp server
    syncer      Generate and install the syncer component top of a k8s cluster
    clean       Clean up the temp directory and remove the kcp plugins

Arguments:
    -v          Version to be installed of the kcp server. Default: `0.8.0`
    -t          Temporary folder where kcp will be installed. Default: `_tmp`
    -c          Name of the k8s cluster where syncer is installed. Default: `kind`
    -w          Workspace to sync resources between kcp and target cluster. Default: `root:my-org`
```

The only prereq to use it is to have access to a physical cluster: kind, ...

**Comment by cmoulliard** [comment]
WDYT about my proposition ? @ncdc @sttts

**Comment by cmoulliard** [comment]
> Maybe let's start there?

A bash script is not a Makefile ;-) The reason why I was proposing this bash script why not the demo or scenario sh script of my project is to simplify the process for the users to play with the technology, to setup new use cases/scenario while the lake file is more confused around testing purposes for the developers/contributors or github actions. Such bash scripts could become part of a contrib folder ?

**Comment by ncdc** [comment]
We had bash scripts for demos in the repo, and they quickly got out of date as the code evolved because no one maintained them.

Our Makefile currently supports starting and stopping kcp but it's tied up in the `test-e2e-shared` target. We could split that apart into separate targets, 1 to start a kcp server, and 1 to stop it.

But we are generally not looking to incorporate bash scripts to start/stop kcp into the repo, as they quickly become out of date as the project evolves.
