### ISSUE TITLE
bug: wrong variable substitution in `kubectl kcp workspace` example

### ISSUE THREAD

**Issue by avinal** [kcp-dev/kcp#2119]
### Describe the bug

The `cliName` is defined as per this logic

https://github.com/kcp-dev/kcp/blob/32fac8a42a32616bc56e653af15b47de022f2165/pkg/cliplugins/workspace/cmd/cmd.go#L72-L75

and is substituted here

https://github.com/kcp-dev/kcp/blob/32fac8a42a32616bc56e653af15b47de022f2165/pkg/cliplugins/workspace/cmd/cmd.go#L81

the doc-generator has no way of deciding what is the path/argument. So it generates the example by substituting `kubectl` instead of `kubectl kcp`. See below

![image](https://user-images.githubusercontent.com/74113200/193617756-7d1dada6-f52e-4fcd-a06c-26f75d6f4b01.png)
 

### Steps To Reproduce

1. Go to `kcp` project root with latest commits
2. Run `make generate-docs`
3. Verify the bug by opening `docs/cli/kcp_workspace.md`

### Expected Behaviour

The example should be generated by substituting `kubectl kcp` instead of `kubectl`.

### Additional Context

This problem was not identified during the testing of PR #2000.

**Comment by hardys** [comment]
This is related to my PR #1901 - that renamed the plugins so that `kubectl workspace` is now valid (does the same as `kubectl kcp workspace`, and the previous aliases `kubectl ws` and `kubectl workspaces` should also still work)

The docs now reference the new `kubectl workspace` syntax which is valid, but I note that the first section of `docs/cli/kcp_workspace.md` does still say `kubectl kcp workspace` - so the following usage examples are now inconsistent.

@ncdc how do we want to handle this, is the `kubectl workspace` plugin now preferred over the `kubectl kcp` subcommand, or do we want to restore the docs to consistently reference `kcp workspaces` ?

**Comment by ncdc** [comment]
I would prefer that we not generate docs and store the generated output in this repo. We can generate and store in the kcp.io or docs.kcp.io repos.

But, to answer your question, I don't think we've decided if we have a preferred option yet. Given that `kubectl kcp workspace` and `kubectl workspace` are equivalent, and people are free to choose, I think anything is ok? I'd actually be fine closing this issue and leaving things as-is.

**Comment by hardys** [comment]
> I'd actually be fine closing this issue and leaving things as-is.

That was my initial reaction too, since the CLI help usage works fine - but if we do want to maintain `./hack/generate/cli-doc/gen-cli-doc.go` then the approach I took using the binary name in #1901 won't work.

An alternative would be to use a different FlagSet name for each CLI path, I pushed #2121 for consideration if we want to go with that approach

**Comment by avinal** [comment]
> I would prefer that we not generate docs and store the generated output in this repo. We can generate and store in the kcp.io or docs.kcp.io repos.

Yes, that would be good. Should I remove them with #2120?

**Comment by ncdc** [comment]
> Should I remove them with https://github.com/kcp-dev/kcp/pull/2120?

Yes please. cc @varshaprasad96 FYI
