### ISSUE TITLE
Replace "virtual workspace" terminology with "view" everywhere

### ISSUE THREAD

**Issue by ncdc** [kcp-dev/kcp#2196]
|Old|New|
|-|-|
|virtual workspace|service|
|APIExport virtual workspace|APIExport service|
|Syncer virtual workspace|Syncer service|
|Workspaces virtual workspace|Workspaces service|
|Initializing workspaces virtual workspace|Initializing workspaces service|
|pkg/virtual|pkg/service|
|cmd/virtual-workspaces|cmd/kcp-services (?)|
|docs/virtual-workspaces.md|docs/services.md|

+ global search for "virtual workspace" and addressing results as needed

**Comment by stevekuznetsov** [comment]
+10000

**Comment by pweil-** [comment]
Some of these make me wonder if we'll be muddying up the term `service`.  A service, in my head, encapsulates the entirety of:

1. The exposed API
2. The virtual workspace view
3. The implementation that fulfils requests 
4. Maybe other things specific to how I implement my service

But I like where this is going.  Is there value in keeping the workspace concept in there?  Like `virtual workspace` -> `service workspace`. Or maybe that confuses the place the service is deployed too, so maybe `virtual workspace` -> `service api workspace`.

**Comment by ncdc** [comment]
@pweil- we need to remove "workspace" from this term - these "things" are not workspaces 😄

**Comment by pweil-** [comment]
😆

**Comment by MikeSpreitzer** [comment]
If I understand correctly, the concept here is very analogous to what, in the database community, is called a "view".  I think we should focus on that term, it will readily lead the reader in the right direction.

If I understand correctly, there is one more critical specific feature of the concept here, which is that a virtual workspace looks the same, to a client, as a plain Kube cluster or a kcp workspace.  That is, it provides what I call a "kube API service".

So I suggest the following possibilities.
- view API service
- view service
- API service view
- service view

I prefer the first two because I think they are less restrictive in semantics.  The latter two suggest that one of these is a view of one API sservice, and I think that cardinality restriction is not something we desire here.

**Comment by stevekuznetsov** [comment]
Yep, we had brandied around the "view" terminology early on as well.

**Comment by ncdc** [comment]
I like `view` as that doesn't conflict with the core v1 `Service` API type. Would also rework `/services` to `/views` in the URLs.

@sttts @davidfestal @stevekuznetsov let's nail this down - would you prefer service or view? (or `<shudder>` do you want to suggest something else?)

**Comment by davidfestal** [comment]
I really prefer `views`

**Comment by ncdc** [comment]
This is what the table looks like for views:

|Old|New|
|-|-|
|virtual workspace|view|
|APIExport virtual workspace|APIExport view|
|Syncer virtual workspace|Syncer view|
|Initializing workspaces virtual workspace|Initializing workspaces view|
|pkg/virtual|pkg/view (or pkg/views)|
|cmd/virtual-workspaces|cmd/kcp-views|
|docs/virtual-workspaces.md|docs/views.md|

**Comment by stevekuznetsov** [comment]
`view` sounds good to me

**Comment by samyak-jn** [comment]
+1 for view :")

**Comment by kasturinarra** [comment]
+1 for view

**Comment by wangke19** [comment]
+1 for view. Just like the concepts of table and view of database.
