### ISSUE TITLE
bug: Synctarget health only takes into account the syncer pod and not the syncer-dns pod.

### ISSUE THREAD

**Issue by jmprusi** [kcp-dev/kcp#2284]
### Describe the bug

Currently a synctarget is marked as ready as soon as the syncer POD sends the heartbeat and it's successful, but the Syncer is now comprised of two distinct deployments: `syncer` and `syncer-dns`. 

Should we take into account 

### Steps To Reproduce

1. Deploy a new syncer on k8s cluster
2. Monitor the Synctarget health on KCP -> should get ready, even if the syncer-dns is not yet running
3. Take down the syncer-dns pod (scale to 0 the deployment)
4. Monitor the synctarget health on KCP -> no changes after a minute

### Expected Behaviour

The Synctarget health should be tied to all the syncer components downstream.

**Comment by davidfestal** [comment]
Well, the thing is that quite soon the `syncer-dns` container will not anymore be starting in the same POD as the Syncer, since there will be one CoreDNS running per KCP user workspace (see issue https://github.com/kcp-dev/kcp/issues/1987).
And those CoreDNS-dedicated Pods would be started/stopped by the Syncer itself.
So, unless the fix is straightforward, I'm not sure it's worth investing time in fixing this issue.

**Comment by davidfestal** [comment]
So it seems this brings up the broader topic of:
- reporting to a resource that syncing is not possible (for a number of reasons, CoreDNS being only one of them)
- possibly including this syncing unrecoverable error condition in the resource scheduling

cf https://github.com/kcp-dev/kcp/issues/1873

**Comment by stevekuznetsov** [comment]
We should prioritize making the system self-consistent and functional at every moment, to the best of our ability. There's always going to be a lot of churn in these early days but if we don't make each step stable-ish for users, they will never stick around long enough to see the future version you're excited about.

**Comment by lionelvillard** [comment]
There is the question of what to report in SyncTarget, either:
- aggregate health: Syncer is healthy when all pods owned by the syncer are healthy (e.g CoreDNS pods)
- individual health: health is reported for each individual pods

Since the number of pods (read deployments) is dynamic (e.g one CoreDNS deployment per workspace), and condition lists are static, aggregate health seems to be the only viable way. When the aggregate health is failing, the condition message should indicate which resource is failing. 

Health aggregation could be easily be done by periodically checking the services liveness probe, for instance when the syncer patches `lastSyncerHeartbeatTime`.

**Comment by lionelvillard** [comment]
Now that https://github.com/kcp-dev/kcp/pull/2293#issuecomment-1314661235 has been merged, `syncer-dns` does not exist anymore.

Closing. @jmprusi, if you feel this is not solved, please reopen.
