### ISSUE TITLE
bug: doc website offers just one release, and it is not a release

### ISSUE THREAD

**Issue by MikeSpreitzer** [kcp-dev/kcp#2697]
### Describe the bug

1. At https://docs.kcp.io/kcp/main/ the "Releases" menu has just one entry --- `main` --- and that is not a _release_.
2. The content of "release" `main` documentation is drawn from the current `main` branch, and should describe how to use what is currently there.  But the quickstart, for example, describes how to use release v0.10.0.

### Steps To Reproduce

RTFM

### Expected Behaviour

I expected there to be a place to hold documentation that is correct for `main` and a way to find and read that documentation.

**Comment by MikeSpreitzer** [comment]
If I understand correctly, #2673 will partially resolve this, by _adding_ actual releases to the "Releases" menu.  It will not resolve the mismatch between the word "releases" and content that is not technically a _release_.

**Comment by avinal** [comment]
I understand the words may not be suitable. But KCP is still developing, so we expect people to use the latest documentation (main branch). In general, we should remove the `main` docs from the menu and only serve the latest stable version docs. This issue was discussed in a meeting and it was decided that we will keep the `main` as default for now.

**Comment by ncdc** [comment]
The header no longer says "releases" and we have docs for main + v0.10
