### ISSUE TITLE
Transparent Multicluster: Cross-workspace LIST/WATCH Controller

### ISSUE THREAD

**Issue by pweil-** [kcp-dev/kcp#284]
Use Case: Transparent Multicluster

Objectives:

- [ ] User can add a second location
- [ ] Deployed application moves between locations when service is disrupted (cluster down)
- [ ] Ingress follows application

Details

Create a controller that LIST/WATCH across a resource in all workspaces and does useful work

**Comment by stevekuznetsov** [comment]
Right now the `Workspace` controller already seeds its informers with a cross-cluster LIST+WATCH and does useful work as a result. I'm a bit confused about the objectives here since they are transparent over physical clusters, whereas the controller bits are transparent across logical clusters. I think we need to figure out which (or both?) we want and what we need to do to that end :)

cc @smarterclayton @imjasonh

**Comment by stevekuznetsov** [comment]
Sounds like we've achieved this one
