### ISSUE TITLE
bug: Use kcp start command

### ISSUE THREAD

**Issue by gitlayzer** [kcp-dev/kcp#3071]
### Describe the bug

When I use kind and execute kcp start, it will not be able to connect to 2379. But if I execute this operation on the master node of the cluster, 6443 is already occupied.

### Steps To Reproduce

root@ubuntu:~/clusters# kcp start
......
[logs.txt](https://github.com/kcp-dev/kcp/files/13854217/logs.txt)

conciler="kcp-resource-permissionclaimlabel" key="leases.v1.coordination.k8s.io::system:admin|kube-system/apiserver-ejk5u55e7knw3kwxkvlwjo2ole"
I0108 00:48:34.474908  495973 permissionclaimlabel_resource_controller.go:105] "queuing resource" reconciler="kcp-permissionclaimlabel" key="leases.v1.coordination.k8s.io::system:admin|kube-system/apiserver-ejk5u55e7knw3kwxkvlwjo2ole"
I0108 00:48:34.474948  495973 permissionclaimlabel_resource_controller.go:141] "processing key" component="kcp" postStartHook="kcp-start-informers" postStartHook="kcp-start-controllers" reconciler="kcp-resource-permissionclaimlabel" key="leases.v1.coordination.k8s.io::system:admin|kube-system/apiserver-ejk5u55e7knw3kwxkvlwjo2ole"

### Expected Behaviour

It should install a set of controllers

**Comment by embik** [comment]
Hi @gitlayzer! Thank you for reaching out. It's not clear from your report what exactly you are reporting, but let's try to figure it out.

> When I use kind and execute kcp start, it will not be able to connect to 2379.

Looking at the logs you have shared, the errors connecting to port 2379 start happening after you terminated/stopped the `kcp start` process. This is probably a race condition in using the embedded etcd, but it should not impact the ability to use kcp while it's running. Can you please confirm this is the behaviour you are reporting?

However, I suspect there is a discrepancy in your expectations. `kcp start` does _not_ install a set of controllers (as you mentioned under "Expected Behaviour"). It starts its own Kubernetes-like API server!

> But if I execute this operation on the master node of the cluster, 6443 is already occupied.

This is expected. You are not installing kcp into Kubernetes with `kcp start`, you are running kcp standalone. That does not require a Kubernetes cluster. If you are looking for running kcp on top of Kubernetes, we maintain a [Helm chart](https://github.com/kcp-dev/helm-charts). But kcp is not an extension to  an existing Kubernetes cluster.
