### ISSUE TITLE
Reconciliation of resources back to pclusters by KCP if deleted by mistake

### ISSUE THREAD

**Issue by samyak-jn** [kcp-dev/kcp#604]
**Describe the bug**
In the perfect world scenario, Ideally, KCP should reconcile back the resources which are by mistake/intentionally deleted from the physical cluster end. The only source of truth in such operation should be done via the KCP end only, but for now if resources are being deleted (need to check for create/update as well) the resources are not reconciled back to their original state of KCP. This should be fixed, as confirmed with team folks as well the tests for this aren't available (might be broken) 

**To Reproduce**
1. Create a ns in kcp and deploy a simple pod to reflect resources in pcluster
2. Using kubeconfig of pcluster, check for ns created 
3. Delete the above namespace from the pcluster end
4. Wait to see the reconciliation to happen but it is broken atm so you wont be getting that ns back but it should ideally come back as it is existing in KCP 

**Expected behavior**
_KCP should reconcile back the resources which are by mistake/intentionally deleted from the physical cluster end_

**Comment by ncdc** [comment]
I think this is because the "spec syncer", which upserts from kcp to pclusters, only watches resources in kcp. If something is deleted in the pcluster, the spec syncer won't know about it. If you make any updates to those resources in kcp (e.g. label or annotate them), they should be rereconciled and recreated. Otherwise, for the time being, you have to wait for the resync period, which is many hours.

**Comment by marun** [comment]
I'm going to take this. Not sure yet if P3 will be doable, but P4 for sure.

**Comment by kasturinarra** [comment]
I have hit below issue as well during my test:
======================================
1) when updated the deployment spec in kcp to have replica count of 12, i see that number of pods run are around 12 in physical cluster which is fine, when i try to update deployment spec in physical cluster to have 14 replicas i see that pods does get increase in number and running oc get deployment also shows the available number as 14 which is not expected as we believe kcp is source of truth

kcp context:
=================
[knarra@knarra kcp]$ oc get deployment 
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
kuard   14/12   14           14          18m

pyhiscal cluster context:
======================
[knarra@knarra ~]$ oc get pods --all-namespaces | grep kuard | wc -l
14

2) When i delete deployment from physical cluster i see that deployments does not show up in pyhsical cluster and ideally they should because kcp is source of truth.

**Comment by ncdc** [comment]
@kasturinarra if you wait a bit, do the deployments go back to 12?

**Comment by kasturinarra** [comment]
> @kasturinarra if you wait a bit, do the deployments go back to 12 ?

you mean when i update the spec in physical cluster ?

**Comment by ncdc** [comment]
Yes, when you update physical cluster to 14, if you wait a bit, does kcp eventually reset it back to 12?

**Comment by kasturinarra** [comment]
> Yes, when you update physical cluster to 14, if you wait a bit, does kcp eventually reset it back to 12?

Nope, not really.  I have just deleted my cluster, i can try again and get back

**Comment by kasturinarra** [comment]
> > Yes, when you update physical cluster to 14, if you wait a bit, does kcp eventually reset it back to 12?
> 
> Nope, not really. I have just deleted my cluster, i can try again on monday and get back but i remember it does not.

**Comment by kasturinarra** [comment]
I tried again and i see that kcp does not eventually reset it back, waited for about an hour and still hit same issue.

[knarra@knarra kcp]$ kubectl get deployment
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
kuard   12/10   12           12          75m

[knarra@knarra kcp]$ oc get pods --all-namespaces | grep kuard
kcp0f3805e02fedad8e8565e6d18e5cf6e4645663e913590b4752129250       kuard-74967d75cc-5hjzn                                                               1/1     Running     0              75m
kcp0f3805e02fedad8e8565e6d18e5cf6e4645663e913590b4752129250       kuard-74967d75cc-6v57w                                                               1/1     Running     0              72m
kcp0f3805e02fedad8e8565e6d18e5cf6e4645663e913590b4752129250       kuard-74967d75cc-gnpdf                                                               1/1     Running     0              75m
kcp0f3805e02fedad8e8565e6d18e5cf6e4645663e913590b4752129250       kuard-74967d75cc-hvn5f                                                               1/1     Running     0              75m
kcp0f3805e02fedad8e8565e6d18e5cf6e4645663e913590b4752129250       kuard-74967d75cc-khzms                                                               1/1     Running     0              75m
kcp0f3805e02fedad8e8565e6d18e5cf6e4645663e913590b4752129250       kuard-74967d75cc-l899p                                                               1/1     Running     0              75m
kcp0f3805e02fedad8e8565e6d18e5cf6e4645663e913590b4752129250       kuard-74967d75cc-nz8hk                                                               1/1     Running     0              75m
kcp0f3805e02fedad8e8565e6d18e5cf6e4645663e913590b4752129250       kuard-74967d75cc-r5dqv                                                               1/1     Running     0              75m
kcp0f3805e02fedad8e8565e6d18e5cf6e4645663e913590b4752129250       kuard-74967d75cc-s7l5z                                                               1/1     Running     0              75m
kcp0f3805e02fedad8e8565e6d18e5cf6e4645663e913590b4752129250       kuard-74967d75cc-v7wh6                                                               1/1     Running     0              75m
kcp0f3805e02fedad8e8565e6d18e5cf6e4645663e913590b4752129250       kuard-74967d75cc-wkstv                                                               1/1     Running     0              75m
kcp0f3805e02fedad8e8565e6d18e5cf6e4645663e913590b4752129250       kuard-74967d75cc-zkr9p                                                               1/1     Running     0              72m

cc: @ncdc

**Comment by sttts** [comment]
Have removed the milestone and the experience-blocker label. This is a nice to have for sure, but it is not a blocker for an MVP.
