### ISSUE TITLE
Provide quickstart instructions for using the kubectl workspace plugin

### ISSUE THREAD

**Issue by marun** [kcp-dev/kcp#687]
Currently there is no obvious documentation of use of the kubectl workspace plugin. The only instructions I could find are bound up on the p2 demo script. Ideally there would be simple introductory instructions for new users in time for p3.

**Comment by pweil-** [comment]
Last day of P3, moving to P4

**Comment by sttts** [comment]
This should be based on https://github.com/kcp-dev/kcp/pull/744.

**Comment by hardys** [comment]
/assign @hardys

Discussed with @davidfestal and agreed to take this - AFAICS the [current docs](https://github.com/kcp-dev/kcp/blob/main/docs/kubectl-kcp-plugin.md) are outdated, and need to be updated to reflect the UX implemented via #778 - it'd also be good if the plugin install was linked/mentioned in the top-level readme and developer quickstart docs.

**Comment by hardys** [comment]
@sttts @davidfestal I have a couple of questions having dug into this:

1. The workspace plurality aliasing seems to be inconsistent, because we only install the `ws` and `workspaces` plugins (not `workspace`)  - Do we want to fix this, and if so would another duplicate plugin be preferred, or else perhaps a Makefile target that can create symlinks instead?

```
$ kubectl get workspaces
NAME    TYPE       PHASE   URL
users   homeroot   Ready   https://10.19.133.66:6443/clusters/root:users
$ kubectl get workspace
NAME    TYPE       PHASE   URL
users   homeroot   Ready   https://10.19.133.66:6443/clusters/root:users
$ kubectl workspaces create foo
Workspace "foo" (type root:organization) created. Waiting for it to be ready...
Workspace "foo" (type root:organization) is ready to use.
$ kubectl workspace create foo2
error: unknown command "workspace" for "kubectl"
```

2. Somewhat related to the above, the help output is inconsistent - `workspace` is mentioned as an alias, but also the usage still references `kubectl kcp workspace` - if we fix the plurality issue, we could detect if/when to include the `kcp` subcommand prefix, does that sound reasonable?

```
$ kubectl workspaces help
Manages KCP workspaces

Usage:
  workspace [create|create-context|use|current|<workspace>|..|.|-|~|<root:absolute:workspace>] [flags]
  workspace [command]

Aliases:
  workspace, ws, workspaces

Examples:

	# shows the workspace you are currently using
	kubectl kcp workspace .

	# enter a given workspace (this will change the current-context of your current KUBECONFIG)
	kubectl kcp workspace use my-workspace
```

**Comment by ncdc** [comment]
> it'd also be good if the plugin install was linked/mentioned in the top-level readme

I am working on this in https://hackmd.io/-YpPqiVsQZyiPIjyoxLiKw

**Comment by hardys** [comment]
Ok I pushed https://github.com/kcp-dev/kcp/pull/1901 aiming to fix the inconsistencies mentioned above, while that doesn't fix this issue it may enable some clearer and/or more consistent docs (I'm assuming we want to switch to referring to the `kubectl ws|workspace|workspaces` plugin, and eventually deprecate the `kcp workspace` subcommand?)
