### ISSUE TITLE
`kubectl kcp workload sync` is not idempotent

### ISSUE THREAD

**Issue by Roming22** [kcp-dev/kcp#920]
**Describe the bug**
Running `kubectl kcp workload sync` twice with the same set of params triggers a failure on the 2nd run because the resources habe already been declared.

**To Reproduce**
1. Run `kubectl kcp workload sync my-test --syncer-image ghcr.io/kcp-dev/kcp/syncer-c2e3073d5026a8f7f2c47a50c16bdbec:41ca72b` -> OK
2. Run `kubectl kcp workload sync my-test --syncer-image ghcr.io/kcp-dev/kcp/syncer-c2e3073d5026a8f7f2c47a50c16bdbec:41ca72b` -> Failure

**Expected behavior**
The resources should be updated if necessary in the background, and the program should exit successfully.

**Additional context**
@marun Related to your latest commits.

**Comment by itdove** [comment]
@ncdc 
1. What should be updated in the workloadcluster as the method provides only the name of the workload.
2. I guess once we will fix the workloadcluster create issue, we will have the same issue with the SA and clusterRoleBinding

Wonder if it exists we just have to skip because I don't see right away which information must be updated.

**Comment by ncdc** [comment]
1. Nothing needs to be updated. I'd say if the workloadcluster exists, keep going instead of erroring.
2. You'll probably want to ensure the SA's ownerref is correct. And make sure the CRB has the right subjects + role ref.
